/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { EmbedService } from "../embed.service";
import { EmbedCreateInput } from "./EmbedCreateInput";
import { EmbedWhereInput } from "./EmbedWhereInput";
import { EmbedWhereUniqueInput } from "./EmbedWhereUniqueInput";
import { EmbedFindManyArgs } from "./EmbedFindManyArgs";
import { EmbedUpdateInput } from "./EmbedUpdateInput";
import { Embed } from "./Embed";

export class EmbedGrpcControllerBase {
  constructor(protected readonly service: EmbedService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Embed })
  @GrpcMethod("EmbedService", "createEmbed")
  async createEmbed(@common.Body() data: EmbedCreateInput): Promise<Embed> {
    return await this.service.createEmbed({
      data: data,
      select: {
        color: true,
        createdAt: true,
        dateCreated: true,
        description: true,
        footer: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Embed] })
  @ApiNestedQuery(EmbedFindManyArgs)
  @GrpcMethod("EmbedService", "embeds")
  async embeds(@common.Req() request: Request): Promise<Embed[]> {
    const args = plainToClass(EmbedFindManyArgs, request.query);
    return this.service.embeds({
      ...args,
      select: {
        color: true,
        createdAt: true,
        dateCreated: true,
        description: true,
        footer: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Embed })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("EmbedService", "embed")
  async embed(
    @common.Param() params: EmbedWhereUniqueInput
  ): Promise<Embed | null> {
    const result = await this.service.embed({
      where: params,
      select: {
        color: true,
        createdAt: true,
        dateCreated: true,
        description: true,
        footer: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Embed })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("EmbedService", "updateEmbed")
  async updateEmbed(
    @common.Param() params: EmbedWhereUniqueInput,
    @common.Body() data: EmbedUpdateInput
  ): Promise<Embed | null> {
    try {
      return await this.service.updateEmbed({
        where: params,
        data: data,
        select: {
          color: true,
          createdAt: true,
          dateCreated: true,
          description: true,
          footer: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Embed })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("EmbedService", "deleteEmbed")
  async deleteEmbed(
    @common.Param() params: EmbedWhereUniqueInput
  ): Promise<Embed | null> {
    try {
      return await this.service.deleteEmbed({
        where: params,
        select: {
          color: true,
          createdAt: true,
          dateCreated: true,
          description: true,
          footer: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
