/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { SlotService } from "../slot.service";
import { SlotCreateInput } from "./SlotCreateInput";
import { SlotWhereInput } from "./SlotWhereInput";
import { SlotWhereUniqueInput } from "./SlotWhereUniqueInput";
import { SlotFindManyArgs } from "./SlotFindManyArgs";
import { SlotUpdateInput } from "./SlotUpdateInput";
import { Slot } from "./Slot";

export class SlotGrpcControllerBase {
  constructor(protected readonly service: SlotService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Slot })
  @GrpcMethod("SlotService", "createSlot")
  async createSlot(@common.Body() data: SlotCreateInput): Promise<Slot> {
    return await this.service.createSlot({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        bid: true,
        createdAt: true,
        description: true,
        id: true,
        metrics: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Slot] })
  @ApiNestedQuery(SlotFindManyArgs)
  @GrpcMethod("SlotService", "slots")
  async slots(@common.Req() request: Request): Promise<Slot[]> {
    const args = plainToClass(SlotFindManyArgs, request.query);
    return this.service.slots({
      ...args,
      select: {
        bid: true,
        createdAt: true,
        description: true,
        id: true,
        metrics: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Slot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("SlotService", "slot")
  async slot(
    @common.Param() params: SlotWhereUniqueInput
  ): Promise<Slot | null> {
    const result = await this.service.slot({
      where: params,
      select: {
        bid: true,
        createdAt: true,
        description: true,
        id: true,
        metrics: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Slot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("SlotService", "updateSlot")
  async updateSlot(
    @common.Param() params: SlotWhereUniqueInput,
    @common.Body() data: SlotUpdateInput
  ): Promise<Slot | null> {
    try {
      return await this.service.updateSlot({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          bid: true,
          createdAt: true,
          description: true,
          id: true,
          metrics: true,
          name: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Slot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("SlotService", "deleteSlot")
  async deleteSlot(
    @common.Param() params: SlotWhereUniqueInput
  ): Promise<Slot | null> {
    try {
      return await this.service.deleteSlot({
        where: params,
        select: {
          bid: true,
          createdAt: true,
          description: true,
          id: true,
          metrics: true,
          name: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
