/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Slot } from "./Slot";
import { SlotCountArgs } from "./SlotCountArgs";
import { SlotFindManyArgs } from "./SlotFindManyArgs";
import { SlotFindUniqueArgs } from "./SlotFindUniqueArgs";
import { CreateSlotArgs } from "./CreateSlotArgs";
import { UpdateSlotArgs } from "./UpdateSlotArgs";
import { DeleteSlotArgs } from "./DeleteSlotArgs";
import { User } from "../../user/base/User";
import { SlotService } from "../slot.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Slot)
export class SlotResolverBase {
  constructor(
    protected readonly service: SlotService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Slot",
    action: "read",
    possession: "any",
  })
  async _slotsMeta(
    @graphql.Args() args: SlotCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Slot])
  @nestAccessControl.UseRoles({
    resource: "Slot",
    action: "read",
    possession: "any",
  })
  async slots(@graphql.Args() args: SlotFindManyArgs): Promise<Slot[]> {
    return this.service.slots(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Slot, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Slot",
    action: "read",
    possession: "own",
  })
  async slot(@graphql.Args() args: SlotFindUniqueArgs): Promise<Slot | null> {
    const result = await this.service.slot(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Slot)
  @nestAccessControl.UseRoles({
    resource: "Slot",
    action: "create",
    possession: "any",
  })
  async createSlot(@graphql.Args() args: CreateSlotArgs): Promise<Slot> {
    return await this.service.createSlot({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Slot)
  @nestAccessControl.UseRoles({
    resource: "Slot",
    action: "update",
    possession: "any",
  })
  async updateSlot(@graphql.Args() args: UpdateSlotArgs): Promise<Slot | null> {
    try {
      return await this.service.updateSlot({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Slot)
  @nestAccessControl.UseRoles({
    resource: "Slot",
    action: "delete",
    possession: "any",
  })
  async deleteSlot(@graphql.Args() args: DeleteSlotArgs): Promise<Slot | null> {
    try {
      return await this.service.deleteSlot(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Slot): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
