/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EntertainmentService } from "../entertainment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EntertainmentCreateInput } from "./EntertainmentCreateInput";
import { Entertainment } from "./Entertainment";
import { EntertainmentFindManyArgs } from "./EntertainmentFindManyArgs";
import { EntertainmentWhereUniqueInput } from "./EntertainmentWhereUniqueInput";
import { EntertainmentUpdateInput } from "./EntertainmentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EntertainmentControllerBase {
  constructor(
    protected readonly service: EntertainmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Entertainment })
  @nestAccessControl.UseRoles({
    resource: "Entertainment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEntertainment(
    @common.Body() data: EntertainmentCreateInput
  ): Promise<Entertainment> {
    return await this.service.createEntertainment({
      data: data,
      select: {
        createdAt: true,
        details: true,
        id: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Entertainment] })
  @ApiNestedQuery(EntertainmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Entertainment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async entertainments(
    @common.Req() request: Request
  ): Promise<Entertainment[]> {
    const args = plainToClass(EntertainmentFindManyArgs, request.query);
    return this.service.entertainments({
      ...args,
      select: {
        createdAt: true,
        details: true,
        id: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Entertainment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Entertainment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async entertainment(
    @common.Param() params: EntertainmentWhereUniqueInput
  ): Promise<Entertainment | null> {
    const result = await this.service.entertainment({
      where: params,
      select: {
        createdAt: true,
        details: true,
        id: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Entertainment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Entertainment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEntertainment(
    @common.Param() params: EntertainmentWhereUniqueInput,
    @common.Body() data: EntertainmentUpdateInput
  ): Promise<Entertainment | null> {
    try {
      return await this.service.updateEntertainment({
        where: params,
        data: data,
        select: {
          createdAt: true,
          details: true,
          id: true,
          name: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Entertainment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Entertainment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEntertainment(
    @common.Param() params: EntertainmentWhereUniqueInput
  ): Promise<Entertainment | null> {
    try {
      return await this.service.deleteEntertainment({
        where: params,
        select: {
          createdAt: true,
          details: true,
          id: true,
          name: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
