/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SecurityCreateNestedManyWithoutUsersInput } from "./SecurityCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { SlotCreateNestedManyWithoutUsersInput } from "./SlotCreateNestedManyWithoutUsersInput";
import { TicketCreateNestedManyWithoutUsersInput } from "./TicketCreateNestedManyWithoutUsersInput";
import { VouchCreateNestedManyWithoutUsersInput } from "./VouchCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  discordId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  reputation?: number | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SecurityCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SecurityCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SecurityCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  securities?: SecurityCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SlotCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SlotCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SlotCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  slots?: SlotCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TicketCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TicketCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TicketCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  tickets?: TicketCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => VouchCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VouchCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VouchCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  vouches?: VouchCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
