/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { UserWhereInput } from "./UserWhereInput";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserUpdateInput } from "./UserUpdateInput";
import { User } from "./User";
import { SecurityFindManyArgs } from "../../security/base/SecurityFindManyArgs";
import { Security } from "../../security/base/Security";
import { SecurityWhereUniqueInput } from "../../security/base/SecurityWhereUniqueInput";
import { SlotFindManyArgs } from "../../slot/base/SlotFindManyArgs";
import { Slot } from "../../slot/base/Slot";
import { SlotWhereUniqueInput } from "../../slot/base/SlotWhereUniqueInput";
import { TicketFindManyArgs } from "../../ticket/base/TicketFindManyArgs";
import { Ticket } from "../../ticket/base/Ticket";
import { TicketWhereUniqueInput } from "../../ticket/base/TicketWhereUniqueInput";
import { VouchFindManyArgs } from "../../vouch/base/VouchFindManyArgs";
import { Vouch } from "../../vouch/base/Vouch";
import { VouchWhereUniqueInput } from "../../vouch/base/VouchWhereUniqueInput";

export class UserGrpcControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  @GrpcMethod("UserService", "createUser")
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        createdAt: true,
        discordId: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        reputation: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  @GrpcMethod("UserService", "users")
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        createdAt: true,
        discordId: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        reputation: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("UserService", "user")
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        createdAt: true,
        discordId: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        reputation: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("UserService", "updateUser")
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          createdAt: true,
          discordId: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          reputation: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("UserService", "deleteUser")
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          createdAt: true,
          discordId: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          reputation: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/securities")
  @ApiNestedQuery(SecurityFindManyArgs)
  @GrpcMethod("UserService", "findManySecurities")
  async findManySecurities(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Security[]> {
    const query = plainToClass(SecurityFindManyArgs, request.query);
    const results = await this.service.findSecurities(params.id, {
      ...query,
      select: {
        action: true,
        createdAt: true,
        date: true,
        id: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/securities")
  @GrpcMethod("UserService", "connectSecurities")
  async connectSecurities(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SecurityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      securities: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/securities")
  @GrpcMethod("UserService", "updateSecurities")
  async updateSecurities(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SecurityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      securities: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/securities")
  @GrpcMethod("UserService", "disconnectSecurities")
  async disconnectSecurities(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SecurityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      securities: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/slots")
  @ApiNestedQuery(SlotFindManyArgs)
  @GrpcMethod("UserService", "findManySlots")
  async findManySlots(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Slot[]> {
    const query = plainToClass(SlotFindManyArgs, request.query);
    const results = await this.service.findSlots(params.id, {
      ...query,
      select: {
        bid: true,
        createdAt: true,
        description: true,
        id: true,
        metrics: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/slots")
  @GrpcMethod("UserService", "connectSlots")
  async connectSlots(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SlotWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      slots: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/slots")
  @GrpcMethod("UserService", "updateSlots")
  async updateSlots(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SlotWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      slots: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/slots")
  @GrpcMethod("UserService", "disconnectSlots")
  async disconnectSlots(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SlotWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      slots: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/tickets")
  @ApiNestedQuery(TicketFindManyArgs)
  @GrpcMethod("UserService", "findManyTickets")
  async findManyTickets(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Ticket[]> {
    const query = plainToClass(TicketFindManyArgs, request.query);
    const results = await this.service.findTickets(params.id, {
      ...query,
      select: {
        createdAt: true,
        dateClosed: true,
        dateCreated: true,
        id: true,
        issue: true,
        priority: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tickets")
  @GrpcMethod("UserService", "connectTickets")
  async connectTickets(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tickets: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tickets")
  @GrpcMethod("UserService", "updateTickets")
  async updateTickets(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tickets: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tickets")
  @GrpcMethod("UserService", "disconnectTickets")
  async disconnectTickets(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tickets: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/vouches")
  @ApiNestedQuery(VouchFindManyArgs)
  @GrpcMethod("UserService", "findManyVouches")
  async findManyVouches(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Vouch[]> {
    const query = plainToClass(VouchFindManyArgs, request.query);
    const results = await this.service.findVouches(params.id, {
      ...query,
      select: {
        badge: true,
        category: true,
        challenge: true,
        createdAt: true,
        date: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        vouchText: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/vouches")
  @GrpcMethod("UserService", "connectVouches")
  async connectVouches(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: VouchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vouches: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/vouches")
  @GrpcMethod("UserService", "updateVouches")
  async updateVouches(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: VouchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vouches: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/vouches")
  @GrpcMethod("UserService", "disconnectVouches")
  async disconnectVouches(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: VouchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vouches: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
