/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SecurityUpdateManyWithoutUsersInput } from "./SecurityUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { SlotUpdateManyWithoutUsersInput } from "./SlotUpdateManyWithoutUsersInput";
import { TicketUpdateManyWithoutUsersInput } from "./TicketUpdateManyWithoutUsersInput";
import { VouchUpdateManyWithoutUsersInput } from "./VouchUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  discordId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  reputation?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SecurityUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SecurityUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SecurityUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  securities?: SecurityUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SlotUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SlotUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SlotUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  slots?: SlotUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TicketUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TicketUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TicketUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  tickets?: TicketUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: () => VouchUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VouchUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VouchUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  vouches?: VouchUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
